/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ljdc.practica3_refactorizacion.cliente.gui;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import ljdc.practica3_refactorizacion.cliente.interfaces.ClienteInterfaz;
import ljdc.practica3_refactorizacion.cliente.interfaces.GUIClienteInterfaz;

/**
 *
 * @author Dave
 */
public class GUICliente extends javax.swing.JFrame implements GUIClienteInterfaz {

    private ClienteInterfaz control;
    
    /**
     * Creates new form GUICliente
     * @param control
     */
    public GUICliente(ClienteInterfaz control) {
        this.control = control;
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_reloj = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_libro = new javax.swing.JTextArea();
        btn_modificarreloj = new javax.swing.JButton();
        btn_pedirlibro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cliente");

        lbl_reloj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_reloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_reloj.setText("00:00:00");

        ta_libro.setColumns(20);
        ta_libro.setRows(5);
        jScrollPane1.setViewportView(ta_libro);

        btn_modificarreloj.setText("Modificar Reloj");
        btn_modificarreloj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarrelojActionPerformed(evt);
            }
        });

        btn_pedirlibro.setText("Pedir Libro");
        btn_pedirlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pedirlibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_modificarreloj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(lbl_reloj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_pedirlibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_modificarreloj)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pedirlibro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificarrelojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarrelojActionPerformed
        this.control.modificarReloj();
    }//GEN-LAST:event_btn_modificarrelojActionPerformed

    private void btn_pedirlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pedirlibroActionPerformed
        this.ta_libro.setText(this.control.pedirLibro());
    }//GEN-LAST:event_btn_pedirlibroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_modificarreloj;
    private javax.swing.JButton btn_pedirlibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_reloj;
    private javax.swing.JTextArea ta_libro;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limpiarCliente() {
        this.ta_libro.setText("");
    }

    @Override
    public void actualizarReloj(String hora) {
        this.lbl_reloj.setText(hora);
    }

    @Override
    public void actualizarLibro(String libro) {
        this.ta_libro.setText(libro);
    }

    @Override
    public boolean reiniciarSesion() {
        int i = JOptionPane.showConfirmDialog(null, "Se reinicio la sesión.\n ¿Deseas continuar (OK) o salir(NO)?");
        //System.out.println("I:"+i);
        return i==JOptionPane.OK_OPTION;
    }

    @Override
    public JLabel obtenerEtiquetaDeReloj() {
        return this.lbl_reloj;
    }

    @Override
    public void mostrar() {
        this.setVisible(true);
    }
}
