/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ljdc.practica3_refactorizacion.general.gui;

import ljdc.practica3_refactorizacion.cliente.backend.Cliente;
import ljdc.practica3_refactorizacion.servidor.backend.Servidor;

/**
 *
 * @author Dave
 */
public class Selector extends javax.swing.JFrame {

    /**
     * Creates new form Selector
     */
    public Selector() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_iniciarcliente = new javax.swing.JButton();
        btn_iniciarservidorprincipal = new javax.swing.JButton();
        btn_configurarservidor = new javax.swing.JButton();
        btn_configurarcliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Practica 3");

        jLabel2.setText("Cliente:");

        jLabel3.setText("Servidor:");

        btn_iniciarcliente.setText("Iniciar Cliente");
        btn_iniciarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarclienteActionPerformed(evt);
            }
        });

        btn_iniciarservidorprincipal.setText("Iniciar Servidor");
        btn_iniciarservidorprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarservidorprincipalActionPerformed(evt);
            }
        });

        btn_configurarservidor.setText("Configuración de Servidor");
        btn_configurarservidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configurarservidorActionPerformed(evt);
            }
        });

        btn_configurarcliente.setText("Configuración de Cliente");
        btn_configurarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configurarclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_iniciarservidorprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_iniciarcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_configurarcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_configurarservidor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btn_iniciarcliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_configurarcliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_iniciarservidorprincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_configurarservidor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_configurarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configurarclienteActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new GUIConfiguracion("cliente").setVisible(true);
        });
    }//GEN-LAST:event_btn_configurarclienteActionPerformed

    private void btn_configurarservidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configurarservidorActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new GUIConfiguracion("servidor").setVisible(true);
        });
    }//GEN-LAST:event_btn_configurarservidorActionPerformed

    private void btn_iniciarservidorprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarservidorprincipalActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(() -> {
            Servidor s = new Servidor();
        });
    }//GEN-LAST:event_btn_iniciarservidorprincipalActionPerformed

    private void btn_iniciarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarclienteActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(() -> {
            Cliente c = new Cliente();
        });
    }//GEN-LAST:event_btn_iniciarclienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_configurarcliente;
    private javax.swing.JButton btn_configurarservidor;
    private javax.swing.JButton btn_iniciarcliente;
    private javax.swing.JButton btn_iniciarservidorprincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
